#!/usr/local/bin/python3
import serial, sys, argparse, time

##
## @brief      Populate the argparse parser with its argument format
##
## @param      parser  pre-instatiated argparse parser
##
## @return     the populated parser
##
def addargs(parser):
	parser.add_argument('port',
											help='Device file or COM port to which the HAMSTER is attached')
	parser.add_argument('-o', '--output_file', default='hamster.log',
											help='Name of the binary file to be generated by this program on your hard drive.')
	parser.add_argument('-b', '--baud', default=115200,
											help='Baud rate for serial comm with the HAMSTER')
	parser.add_argument('-f', '--flight', action='store_true',
											help='If this flag is passed, the script will expect to interact with \
												  the HAMSTER FSW, starting in state STANDBY. Otherwise, it will \
												  expect to interact with the FlashLog test suite.')
	return parser

######### MAIN

def main():
	parser = argparse.ArgumentParser(description='This program grabs a binary dump from the FlashLog. To use it,\
				  you must first flash the FlashLog Test Suite to the HAMSTER using the `flash-test_flash` make target.\
				  If the output of this program is a garbage binary file, you probably aren\'t using the right\
				  baud rate. ')
	addargs(parser)
	args = parser.parse_args()

	# 2 second read timeout
	with serial.Serial(args.port, args.baud, timeout=2) as ser, open(args.output_file, 'wb') as ofile:
		bytes_received = 0
		time.sleep(2)
		try:
			if args.flight:
				print('Expecting to interact with the HAMSTER FSW, currently in state STANDBY.')
				print('Initiating hex dump...')
				ser.write('dump\n'.encode('ascii')) #dump command is valid from STANDBY state
			else:
				print('Expecting to interact with the FlashLog Test Suite')

				#first, send a break to reset the flash program, and wait a second
				print('Starting MBED FlashLog test program...')
				ser.send_break()
				time.sleep(3)

				print('Initiating binary dump...')
				ser.write('13\n'.encode('ascii')) #bindump is test #13

			# then just read the serial line forever until it stops sending.
			byte = ser.read(1)
			while len(byte) > 0:
				bytes_received = bytes_received + 1
				if bytes_received % 1000 == 0:
					print('\r{} bytes received.\t'.format(bytes_received), end='')
				ofile.write(byte)
				byte = ser.read(1)
		except KeyboardInterrupt:
			#if we ctrl+c out of the progarm, stop the MBED running
			print('\nHalting MBED program execution (will only work if connected by USB)...')
			ser.send_break()

		print('{} chars written to "{}".'.format(bytes_received, args.output_file))

if __name__ == '__main__':
	sys.exit(main())
